<a href="https://colab.research.google.com/github/centbenjamin6-dot/HEALTH-INFOMATICS/blob/main/N1_2_strings_fstrings_lists_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# N1.2 · Strings, f-strings and Lists

**Day 1 · about 90 minutes** · *Health Analytics and Sustainability (ESG) course*

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/festusoladayoonline-debug/Health_Informatics/blob/main/notebooks/day1/N1.2_strings_fstrings_lists_colab.ipynb)

**You are using Google Colab.** Notebooks open in your browser and run on Google's computers, so there is nothing to install. If Colab says the session has disconnected, click **Reconnect** and run the cells again from the top (Runtime → Run all).

### 🎯 What you will be able to do after this notebook
- Clean and slice **text** (strings)
- Build tidy report lines with **f-strings**
- Store, index, slice and extend **lists**
- Compute a **mean** with `sum( )` and `len( )` and format a patient summary line

### 🗺️ Roadmap
| Part | Topic | Time |
|---|---|---|
| A | Strings: working with text | 25 min |
| B | f-strings: formatted output | 20 min |
| C | Lists: collections of values | 30 min |
| D | Putting it together: patient summaries | 15 min |

**Reminder:** run cells with **Shift + Enter**, in order. `____` means *fill in the blank*. A ❌ means *not quite yet*. Legend: 📘 read · ▶️ run · ✏️ fill in · 🧑‍💻 your turn · 🎯 check · 💡 hint.

## Setup
▶️ Run the checker cell once (the same helper as in N1.1).

In [1]:
# 🧰 COURSE HELPER: just run this cell once. (You will understand every line by Day 2.)
_results = {}

def _report(name, ok, message):
    _results[name] = ok
    print(("✅ " if ok else "❌ ") + message)

def check(name, expected, tol=0, hint=""):
    """Is the variable called `name` equal to the expected answer?"""
    if name not in globals():
        _report(name, False, f"{name}: I can't find this variable yet. Fill in the blank or write your code, then run the cell again. {hint}".strip())
        return
    value = globals()[name]
    try:
        if isinstance(expected, bool):
            ok = isinstance(value, bool) and value == expected
        elif isinstance(expected, (int, float)):
            ok = (not isinstance(value, bool)) and abs(value - expected) <= tol
        else:
            ok = value == expected
    except Exception:
        ok = False
    if ok:
        _report(name, True, f"{name}: correct!")
    else:
        _report(name, False, f"{name}: not quite yet. Your value is {value!r}. {hint}".strip())

def check_type(name, expected_type, hint=""):
    """Does the variable called `name` hold the expected type of value?"""
    if name not in globals():
        _report(name, False, f"{name}: I can't find this variable yet. {hint}".strip())
        return
    value = globals()[name]
    ok = type(value) is expected_type
    if ok:
        _report(name, True, f"{name}: correct type ({expected_type.__name__})!")
    else:
        _report(name, False, f"{name}: expected type {expected_type.__name__}, but yours is {type(value).__name__}. {hint}".strip())

def check_that(name, test, hint=""):
    """Does the value in `name` pass a custom test?"""
    if name not in globals():
        _report(name, False, f"{name}: I can't find this variable yet. {hint}".strip())
        return
    value = globals()[name]
    try:
        ok = bool(test(value))
    except Exception:
        ok = False
    if ok:
        _report(name, True, f"{name}: correct!")
    else:
        _report(name, False, f"{name}: not quite yet. Your value is {value!r}. {hint}".strip())

def progress():
    passed, total = sum(_results.values()), len(_results)
    print(f"You have passed {passed} of {total} checks so far.")
    if total > 0 and passed == total:
        print("🎉 All checks passed. Well done!")

## Part A · Strings: working with text
📘 A **string** is a piece of text inside quotes. Health data is full of text: patient IDs, diagnoses, drug names, lab codes.

### ▶️ Worked example A1: the basics

In [2]:
sex = "female"
drug = 'metformin'                       # single or double quotes both work

print(sex + " / " + drug)                # + joins text ("concatenation")
print("-" * 20)                          # * repeats text: a quick divider line
print(len(drug))                         # len() counts characters: 9

female / metformin
--------------------
9


### 📘 Methods: actions that belong to the text
A **method** is a function attached to a value with a **dot**. You write the value, a dot, the method name, and brackets.
```
drug.upper()
│    │ └── brackets (some methods need an input inside; this one does not)
│    └── the method name ("give me the UPPERCASE version")
└── the value the method acts on
```
| Method | What it does | Example | Result |
|---|---|---|---|
| `.upper()` | all capitals | `"aspirin".upper()` | `"ASPIRIN"` |
| `.lower()` | all lower case | `"PRT".lower()` | `"prt"` |
| `.title()` | Capital First Letters | `"type 2 diabetes".title()` | `"Type 2 Diabetes"` |
| `.strip()` | remove spaces at both ends | `"  P017 ".strip()` | `"P017"` |
| `.replace(a, b)` | swap text `a` for `b` | `"P-017".replace("-", "")` | `"P017"` |
| `.startswith(x)` | True/False | `"GLU-12".startswith("GLU")` | `True` |

⚠️ Methods **return a new string**; they do not change the original. To keep the result, store it: `clean = text.strip()`.

### ▶️ Worked example A2: methods in action

In [3]:
raw_code = "  glu-2024  "
print(raw_code.strip())                       # remove the spaces
print(raw_code.strip().upper())               # chain methods: strip, then capitalise
print(raw_code.strip().replace("-", "_"))     # swap - for _
print("GLU-12".startswith("GLU"))             # True

glu-2024
GLU-2024
glu_2024
True


### ✏️ Exercise 1.2.1 · Clean a patient ID
The ID arrived as `"  p017 "` (spaces and lower case). Produce the clean form `"P017"` by chaining two methods.

In [6]:
patient_id_raw = "  p017 "
clean_id = (patient_id_raw.strip().upper())
print(clean_id)

P017


🎯 **Check**

In [7]:
check("clean_id", "P017", hint="Chain .strip() and .upper().")

✅ clean_id: correct!


### ✏️ Exercise 1.2.2 · Diagnosis text
Turn the diagnosis into title case and count its characters (spaces count too).

In [16]:
diagnosis = "type 2 diabetes"
diagnosis_title = diagnosis.title()
diagnosis_length = len(diagnosis)

🎯 **Check**

In [17]:
check("diagnosis_title", "Type 2 Diabetes")
check("diagnosis_length", 15, hint="len() counts every character, including spaces.")

✅ diagnosis_title: correct!
✅ diagnosis_length: correct!


### 📘 Indexing and slicing text
Every character has a position number, called its **index**. **Counting starts at 0!**
```
text       G  L  U  -  2  0  2  4  -  0  0  4  2
index      0  1  2  3  4  5  6  7  8  9  10 11 12
negative  -13 ...                     -4 -3 -2 -1
```
| Syntax | Meaning | On `"GLU-2024-0042"` |
|---|---|---|
| `text[0]` | the first character | `"G"` |
| `text[-1]` | the last character | `"2"` |
| `text[0:3]` | from index 0 **up to but not including** 3 | `"GLU"` |
| `text[:3]` | same: start at the beginning | `"GLU"` |
| `text[4:8]` | index 4, 5, 6, 7 | `"2024"` |
| `text[-4:]` | the last four characters | `"0042"` |

### ▶️ Worked example A3: slicing a lab code

In [18]:
sample_code = "BP-2025-0913"       # blood-pressure sample, year 2025, number 0913

print(sample_code[0])              # first character: B
print(sample_code[0:2])            # BP
print(sample_code[3:7])            # 2025
print(sample_code[-4:])            # 0913

B
BP
2025
0913


### 🧑‍💻 Exercise 1.2.3 · Decode a lab code
The lab code is `"GLU-2024-0042"` (test, year, number). Store its three parts in `lab_test`, `lab_year` and `lab_number` using slicing.

In [22]:
lab_code = "GLU-2024-0042"

# lab_test   -> the first 3 characters
# lab_year   -> the 4 digits of the year
# lab_number -> the last 4 characters
lab_test = "GLU"
lab_year = "2024"
lab_number = "0042"

💡 <details><summary>Hint</summary>Indexes: G=0, L=1, U=2, - =3, then the year starts at 4 and ends before 8. The number is the last four characters: <code>[-4:]</code>.</details>

🎯 **Check**

In [23]:
check("lab_test", "GLU")
check("lab_year", "2024")
check("lab_number", "0042")

✅ lab_test: correct!
✅ lab_year: correct!
✅ lab_number: correct!


## Part B · f-strings: formatted output
📘 An **f-string** puts variables **inside** text. Write the letter `f` immediately before the opening quote, and put variables in curly braces `{ }`.
```
f"BMI: {bmi:.1f}"
│                    
│    f before the quote = "this is an f-string"
│    {bmi}    = insert the value of the variable bmi here
│    :.1f     = format it with 1 digit after the decimal point
```
| Format | Meaning | Example (value 22.857) | Output |
|---|---|---|---|
| `{x}` | as it is | `f"{x}"` | `22.857` |
| `{x:.1f}` | 1 decimal | `f"{x:.1f}"` | `22.9` |
| `{x:.0f}` | no decimals | `f"{x:.0f}"` | `23` |
| `{x:,}` | thousands separator | `f"{10330000:,}"` | `10,330,000` |
| `{x:.1%}` | percentage | `f"{0.864:.1%}"` | `86.4%` |

### ▶️ Worked example B1

In [24]:
weight_kg = 70.0
height_m = 1.75
bmi = weight_kg / height_m ** 2

print(f"Weight: {weight_kg} kg")
print(f"BMI: {bmi}")            # too many decimals
print(f"BMI: {bmi:.1f}")        # tidy: 22.9
print(f"Rounded to whole number: {bmi:.0f}")

Weight: 70.0 kg
BMI: 22.857142857142858
BMI: 22.9
Rounded to whole number: 23


### ✏️ Exercise 1.2.4 · A report line
Complete the f-string so that `report` reads exactly: `Weight: 70.0 kg, BMI: 22.9`.

In [25]:
weight_kg = 70.0
bmi = 70.0 / 1.75 ** 2
report = f"Weight: {weight_kg} kg, BMI: {22.9}"
print(report)

Weight: 70.0 kg, BMI: 22.9


🎯 **Check**

In [26]:
check("report", "Weight: 70.0 kg, BMI: 22.9", hint="Format bmi with :.1f inside the braces.")

✅ report: correct!


### ✏️ Exercise 1.2.5 · Vaccination coverage
In a district, **4,321 of 5,000** people are vaccinated. Show the coverage as a percentage with one decimal (`86.4%`).

In [31]:
vaccinated = 4321
population = 5000
coverage_text = f"Coverage: {vaccinated/population:.1%}"
print(coverage_text)

Coverage: 86.4%


🎯 **Check**

In [32]:
check("coverage_text", "Coverage: 86.4%")

✅ coverage_text: correct!


### 🧑‍💻 Exercise 1.2.6 · Big numbers
Store the text `Population: 10,330,000` in `population_text`, using the number `population_pt` and the thousands-separator format `:,`.

In [33]:
population_pt = 10330000

# population_text should read: Population: 10,330,000
population_text = f"Population: {population_pt:,}"
print(population_text)

Population: 10,330,000


🎯 **Check**

In [34]:
check("population_text", "Population: 10,330,000", hint='Use {population_pt:,} inside an f-string.')

✅ population_text: correct!


## Part C · Lists: collections of values
📘 A **list** stores several values in order, inside square brackets, separated by commas. Perfect for a set of measurements.
```
heart_rates = [72, 88, 65, 90, 78]
│             │└──────────────────┘
│             │        └── the items, separated by commas
│             └── square brackets [ ] mark a list
└── the variable name
```
Lists use the **same index rules as text**: start at 0, negative numbers count from the end, slices `[a:b]` stop before `b`.
```
value   72  88  65  90  78
index    0   1   2   3   4
negative -5  -4  -3  -2  -1
```
| Task | Syntax | Result on `[72, 88, 65, 90, 78]` |
|---|---|---|
| first item | `heart_rates[0]` | `72` |
| last item | `heart_rates[-1]` | `78` |
| a slice | `heart_rates[1:4]` | `[88, 65, 90]` |
| number of items | `len(heart_rates)` | `5` |
| add an item at the end | `heart_rates.append(84)` | list becomes 6 long |
| total / smallest / largest | `sum( )` / `min( )` / `max( )` | `393` / `65` / `90` |
| sorted copy | `sorted(heart_rates)` | `[65, 72, 78, 88, 90]` |
| is it in the list? | `"aspirin" in medications` | `True` or `False` |

### ▶️ Worked example C1: indexing and slicing

In [35]:
heart_rates = [72, 88, 65, 90, 78]

print(heart_rates[0])       # first item
print(heart_rates[-1])      # last item
print(heart_rates[1:4])     # items at index 1, 2, 3
print(len(heart_rates))     # how many items

72
78
[88, 65, 90]
5


### ▶️ Worked example C2: growing a list
⚠️ **Tip:** keep the line that *creates* the list in the **same cell** as `.append(...)`. Then re-running the cell never adds the value twice.

In [36]:
weights_kg = [62.5, 80.1, 71.3]
weights_kg.append(90.4)        # a new patient arrives
weights_kg.append(55.0)
print(weights_kg)
print("Number of patients:", len(weights_kg))

[62.5, 80.1, 71.3, 90.4, 55.0]
Number of patients: 5


### ✏️ Exercise 1.2.7 · Pick items by position
Use the `heart_rates` list from Worked example C1.

In [38]:
heart_rates = [72, 88, 65, 90, 78]
first_rate = heart_rates[0]
last_rate = heart_rates[-1]
middle_three = heart_rates[1:4]

🎯 **Check**

In [39]:
check("first_rate", 72)
check("last_rate", 78)
check("middle_three", [88, 65, 90], hint="A slice [1:4] stops before index 4.")

✅ first_rate: correct!
✅ last_rate: correct!
✅ middle_three: correct!


### ✏️ Exercise 1.2.8 · A new reading arrives
A new heart-rate reading of **84** must be added at the end. Then count the readings.

In [40]:
readings = [72, 88, 65, 90, 78]
readings.append(84)
number_of_readings = len(readings)
print(readings)
print(number_of_readings)

[72, 88, 65, 90, 78, 84]
6


🎯 **Check**

In [41]:
check("readings", [72, 88, 65, 90, 78, 84])
check("number_of_readings", 6)

✅ readings: correct!
✅ number_of_readings: correct!


### 🧑‍💻 Exercise 1.2.9 · Summarise the heart rates
Using the list `heart_rates` (5 values), store:
- `mean_rate`: the **mean** (total ÷ number of items, using `sum( )` and `len( )`)
- `highest_rate`: the largest value
- `lowest_rate`: the smallest value
- `sorted_rates`: the values in ascending order

In [42]:
heart_rates = [72, 88, 65, 90, 78]

# Write your code here
mean_rate = sum(heart_rates) / len(heart_rates)
highest_rate = max(heart_rates)
lowest_rate = min(heart_rates)
sorted_rates = sorted(heart_rates)
print(mean_rate)
print(highest_rate)
print(lowest_rate)
print(sorted_rates)

78.6
90
65
[65, 72, 78, 88, 90]


💡 <details><summary>Hint</summary>The mean is <code>sum(heart_rates) / len(heart_rates)</code>. It should be 78.6.</details>

🎯 **Check**

In [43]:
check("mean_rate", 78.6, tol=0.001)
check("highest_rate", 90)
check("lowest_rate", 65)
check("sorted_rates", [65, 72, 78, 88, 90])

✅ mean_rate: correct!
✅ highest_rate: correct!
✅ lowest_rate: correct!
✅ sorted_rates: correct!


### ✏️ Exercise 1.2.10 · Medication check
The keyword `in` asks *"is this item in the list?"* and answers `True` or `False`.

In [44]:
medications = ["metformin", "aspirin", "atorvastatin"]
takes_aspirin = True
takes_insulin = False

🎯 **Check**

In [45]:
check("takes_aspirin", True)
check("takes_insulin", False)

✅ takes_aspirin: correct!
✅ takes_insulin: correct!


## Part D · Putting it together: patient summaries
📘 Three lists hold the data for **five patients**. Position **0** is patient 1, position **1** is patient 2, and so on: the same position in each list belongs to the same patient.

### ▶️ Worked example D1: patient 1 and the group mean

In [46]:
weights_kg = [62.5, 80.1, 71.3, 90.4, 55.0]
heights_m  = [1.60, 1.80, 1.75, 1.85, 1.58]

# Patient 1 is at index 0
bmi_1 = weights_kg[0] / heights_m[0] ** 2
summary_1 = f"Patient 1: {weights_kg[0]} kg, BMI {bmi_1:.1f}"
print(summary_1)                                         # Patient 1: 62.5 kg, BMI 24.4

mean_of_weights = sum(weights_kg) / len(weights_kg)
print(f"Mean weight: {mean_of_weights:.1f} kg")          # Mean weight: 71.9 kg

Patient 1: 62.5 kg, BMI 24.4
Mean weight: 71.9 kg


### ✏️ Exercise 1.2.11 · Mean, third and last weight
Use the `weights_kg` list above.

In [10]:
weights_kg = [62.5, 80.1, 71.3, 90.4, 55.0]
mean_weight = sum(weights_kg) / len(weights_kg)
third_weight = weights_kg[2]
last_weight = weights_kg[-1]
print(mean_weight)
print(third_weight)
print(last_weight)

71.86
71.3
55.0


🎯 **Check**

In [12]:
check("mean_weight", 71.86, tol=0.001)
check("third_weight", 71.3, hint="The third item has index 2.")
check("last_weight", 55.0)

NameError: name 'check' is not defined

### ✏️ Exercise 1.2.12 · Patient 2
Complete the summary for **patient 2**. Their data are at index **1**. Expected: `Patient 2: 80.1 kg, BMI 24.7`.

In [14]:
weights_kg = [62.5, 80.1, 71.3, 90.4, 55.0]
heights_m  = [1.60, 1.80, 1.75, 1.85, 1.58]

bmi_2 = weights_kg[1] / heights_m[1] ** 2
summary_2 = f"Patient 2: {weights_kg[1]} kg, BMI {bmi_2}"
print(summary_2)

Patient 2: 80.1 kg, BMI 24.722222222222218


🎯 **Check**

In [15]:
check("summary_2", "Patient 2: 80.1 kg, BMI 24.7")

NameError: name 'check' is not defined

### 🧑‍💻 Exercise 1.2.13 · Patient 3
Write the summary for **patient 3** (index **2**) in exactly the same format. Store it in `summary_3`. Expected: `Patient 3: 71.3 kg, BMI 23.3`.

In [16]:
weights_kg = [62.5, 80.1, 71.3, 90.4, 55.0]
heights_m  = [1.60, 1.80, 1.75, 1.85, 1.58]

# Write your code here (calculate bmi_3, then build summary_3)
bmi_2 = weights_kg[1] / heights_m[1] ** 2
summary_3 = f"Patient 3: {weights_kg[2]} kg, BMI {bmi_2}"
print(summary_2)

Patient 2: 80.1 kg, BMI 24.722222222222218


💡 <details><summary>Hint</summary>Copy the code from Exercise 1.2.12 and change every <code>1</code> that means &quot;patient 2&quot; to the right index and label.</details>

🎯 **Check**

In [17]:
check("summary_3", "Patient 3: 71.3 kg, BMI 23.3")

NameError: name 'check' is not defined

### 💭 Notice something?
You wrote almost the same code three times (patients 1, 2, 3). Imagine 5,000 patients! On **Day 2** you will learn **loops**, which repeat code automatically.

## 🧾 Recap: your cheat sheet
| Idea | Syntax | Example |
|---|---|---|
| Join text | `+` | `"P" + "017"` |
| Text methods | `.strip() .upper() .lower() .title() .replace(a, b)` | `"  p17 ".strip().upper()` |
| Slice | `text[start:stop]` (stop is excluded) | `"GLU-2024"[4:8]` → `"2024"` |
| f-string | `f"... {value:.1f} ..."` | `f"BMI {bmi:.1f}"` |
| Make a list | `[a, b, c]` | `[72, 88, 65]` |
| Index | `my_list[0]`, `my_list[-1]` | first, last |
| Add / count | `.append(x)`, `len(x)` | |
| Summaries | `sum() min() max() sorted()` | `sum(x) / len(x)` = mean |
| Membership | `x in my_list` | `"aspirin" in medications` |

### Common slips
- Forgetting the **`f`** before the quote → the braces are printed literally.
- **Off-by-one:** the first item is index **0**, and a slice stops **before** its end index.
- **IndexError:** asking for a position that does not exist (for example `heart_rates[10]` in a 5-item list).
- **Quote mix-ups:** starting with `"` and ending with `'`.

**Next:** N1.3, *Dictionaries and unit conversion*.

### 📊 Your progress

In [18]:
progress()   # shows how many checks you have passed

NameError: name 'progress' is not defined

💾 **Save your work:** File → *Save a copy in Drive* (and optionally *Download .ipynb*).